/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.3.21")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    maven(url = "http://dl.bintray.com/kyonifer/maven")
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("com.kyonifer:koma-core-ejml:0.12")
    implementation("com.kyonifer:koma-plotting:0.12")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application.
    mainClassName = "kontrol.AppKt"
}

kotlin.sourceSets.main {
  kotlin.srcDir("src/main/kotlin")
}

kotlin.sourceSets.test {
  kotlin.srcDir("src/test/kotlin")
}
